apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hospital-2-ca-certificate
spec:
  secretName: hospital-2-ca-key-pair
  duration: 87660h # 10y
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "Hospital 2 Admin"
  commonName: "Hospital 2 Admin"
  isCA: true
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    name: hospital-2-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io