apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hospital-2-mysql
spec:
  secretName: hospital-2-mysql-server-certs
  duration: 87660h
  renewBefore: 360h
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  usages:
    - digital signature
    - key encipherment
    - server auth
  subject:
    organizations:
      - mysql
  commonName: hospital-2-mysql
  dnsNames:
    - hospital-2-mysql-sts-0
    - hospital-2-mysql-sts-0.mysql.default.svc.cluster.local
  issuerRef:
    name: hospital-2-ca-issuer
    kind: Issuer
    group: cert-manager.io