apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hospital-2-mysql-openemr-client
spec:
  secretName: hospital-2-mysql-openemr-client-certs
  duration: 87660h
  renewBefore: 360h
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  usages:
    - digital signature
    - key encipherment
    - client auth
  subject:
    organizations:
      - openemr
  commonName: hospital-2-openemr
  issuerRef:
    name: hospital-2-ca-issuer
    kind: Issuer
    group: cert-manager.io