apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hospital-2-mysql-replication
spec:
  secretName: hospital-2-mysql-replication-certs
  duration: 87660h
  renewBefore: 360h
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  subject:
    organizations:
      - mysql
  commonName: hospital-2-mysql
  issuerRef:
    name: hospital-2-ca-issuer
    kind: Issuer
    group: cert-manager.io