apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    name: hospital-2-openemr
  name: hospital-2-openemr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hospital-2-openemr
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:
        name: hospital-2-openemr
    spec:
      initContainers:
      - name: hospital-2-init-mysql-wait
        image: busybox:1.28
        command:
        - sh
        - -c
        - "until nslookup hospital-2-mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done"
      - name: hospital-2-init-redis-wait
        image: busybox:1.28
        command:
        - sh
        - -c
        - "until nslookup redisproxy.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis; sleep 2; done"
      containers:
      - env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: openemr-credentials
              key: mysql-pass
        - name: MYSQL_ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: MYSQL_USER
          value: "openemr"
        - name: OE_PASS
          valueFrom:
            secretKeyRef:
              name: openemr-credentials
              key: admin-pass
        - name: OE_USER
          value: "admin"
        - name: REDIS_SERVER
          value: "redisproxy"
        - name: REDIS_PASSWORD
          value: "defaultpassword"
        - name: SWARM_MODE
          value: "yes"
        - name: FORCE_DATABASE_SSL_CONNECT
        # uncomment below line (and comment above line) if forcing mysql x509
        #- name: FORCE_DATABASE_X509_CONNECT
          value: "1"
        image: openemr/openemr:7.0.2
        name: hospital-2-openemr
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: 1000m
            memory: 1G
        volumeMounts:
        - mountPath: /root/certs/mysql/server
          name: hospital-2-mysql-openemr-client-certs
        - mountPath: /var/www/localhost/htdocs/openemr/sites
          name: hospital-2-websitevolume
        - mountPath: /etc/ssl
          name: hospital-2-sslvolume
        - mountPath: /etc/letsencrypt
          name: hospital-2-letsencryptvolume
      restartPolicy: Always     
      volumes:
      - name: hospital-2-mysql-openemr-client-certs
        secret:
          secretName: hospital-2-mysql-openemr-client-certs
          items:
          - key: ca.crt
            path: mysql-ca
          # uncomment below if forcing mysql x509
          #- key: tls.crt
          #  path: mysql-cert
          #- key: tls.key
          #  path: mysql-key
      - name: hospital-2-websitevolume
        persistentVolumeClaim:
          claimName: hospital-2-websitevolume
      - name: hospital-2-sslvolume
        persistentVolumeClaim:
          claimName: hospital-2-sslvolume
      - name: hospital-2-letsencryptvolume
        persistentVolumeClaim:
          claimName: hospital-2-letsencryptvolume
