apiVersion: v1
kind: Service
metadata:  
  labels:
    name: hospital-2-openemr
  name: hospital-2-openemr
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    targetPort: 80
    protocol: TCP
    nodePort: 30002
  - name: "https"
    port: 8090
    targetPort: 443
  selector:
    name: hospital-2-openemr
