# note the service always directs to the primary (and not the replica, which if allowed
#  would break horribly since replicas are just set for mariadb replication) via the selector
apiVersion: v1
kind: Service
metadata:
  name: mysql-2
  labels:
    app: mysql-2
spec:
  ports:
  - port: 3306
    name: mysql-port
  # - protocol: TCP
  #   port: 9104
  #   targetPort: 9104
  #   name: metrics
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: mysql-2-sts-0