# four node (three workers) cluster config
#   Supports shared volumes over different nodes, however, to support this,
#   have hard-coded hostpath to use /tmp/hostpath-provisioner in this script
#   and in the kind-pvc-hostpath.yaml (custom storage class) script.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30001
      hostPort: 30001
      protocol: TCP
    - containerPort: 30002
      hostPort: 30002
      protocol: TCP
    - containerPort: 30003
      hostPort: 30003
      protocol: TCP
    - containerPort: 30004
      hostPort: 30004
      protocol: TCP
    - containerPort: 30005
      hostPort: 30005
      protocol: TCP
    - containerPort: 30006
      hostPort: 30006
      protocol: TCP
    - containerPort: 30007
      hostPort: 30007
      protocol: TCP
    - containerPort: 30008
      hostPort: 30008
      protocol: TCP
    - containerPort: 30009
      hostPort: 30009
      protocol: TCP
  extraMounts:
  - hostPath: ./kind-pvc-hostpath.yaml
    containerPath: /kind/manifests/default-storage.yaml
  - hostPath: /tmp/hostpath-provisioner
    containerPath: /tmp/hostpath-provisioner
- role:  worker
  extraMounts:
  - hostPath: /tmp/hostpath-provisioner
    containerPath: /tmp/hostpath-provisioner
- role:  worker
  extraMounts:
  - hostPath: /tmp/hostpath-provisioner
    containerPath: /tmp/hostpath-provisioner
- role: worker
  extraMounts:
  - hostPath: /tmp/hostpath-provisioner
    containerPath: /tmp/hostpath-provisioner