apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-2-redis-acl
data:
  users.acl: |
    user admin on >adminpassword ~* &* +@all
    user replication on >replicationpassword +psync +replconf +ping
    user default on >defaultpassword ~* &* +@all -@dangerous