apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-2-redisproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-2-redisproxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hospital-2-redisproxy
    spec:
      initContainers:
      - name: proxy-init-redis-wait-1
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup hospital-2-redis-0.hospital-2-redis; do echo waiting for hospital-2-redis-0; sleep 10; done"]
      - name: proxy-init-redis-wait-2
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup hospital-2-redis-1.hospital-2-redis; do echo waiting for hospital-2-redis-1; sleep 10; done"]
      - name: proxy-init-redis-wait-3
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup hospital-2-redis-2.hospital-2-redis; do echo waiting for hospital-2-redis-2; sleep 10; done"]
      containers:
      - env:
        - name: PIPY_CONFIG_FILE
          value: /proxy/proxy.js
        image: naqvis/pipy:0.30.0-23
        name: hospital-2-redisproxy
        volumeMounts:
        - name: hospital-2-redisproxyconf
          mountPath: /proxy
      volumes:
      - name: hospital-2-redisproxyconf
        configMap:
          name: hospital-2-pipy-config
          items:
            - key: config.json
              path: config/config.json
            - key: proxy.js
              path: proxy.js