apiVersion: v1
kind: Service
metadata:
  name: hospital-2-redisproxy
spec:
  clusterIP: None # "None" make it a headless service. No cluster IP.
  ports:
    - port: 6379
      targetPort: 6379
      name: hospital-2-redisproxy
  selector:
    app: hospital-2-redisproxy