apiVersion: v1
kind: Service
metadata:  
  labels:
    name: openemr
  name: openemr
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    targetPort: 80
    protocol: TCP
    nodePort: 30001
  - name: "https"
    port: 8090
    targetPort: 443
  selector:
    name: openemr
